### ISSUE TITLE
Добавить в инструкцию по postgre ссылку на инструкцию по запуску под WSL

### ISSUE THREAD

**Issue by ya-pekatoros** [Hexlet/ru-instructions#11]
Добрый день. Команды из инструкции не актуальны для работы с WSL. По ссылке есть работающая схема.

https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-database

**Comment by DmitriiGoltsov** [comment]
Готов взять ишью на себя.

**Comment by DmitriiGoltsov** [comment]
Запросил пулреквест по этому issue. 

> Добрый день. Команды из инструкции не актуальны для работы с WSL. По ссылке есть работающая схема.
> 
> https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-database
