### ISSUE TITLE
Добавить инструкцию по установке docker

### ISSUE THREAD

**Issue by ssssank** [Hexlet/ru-instructions#23]
Нужна инструкция по установке и запуску докера. За основу можно взять [официальную инструкцию](https://docs.docker.com/get-docker/), а также можно подглядывать в другие инструкции из этого репозитория

**Comment by Dzigr** [comment]
Привет. Возьму данное задание

**Comment by Dzigr** [comment]
Closed [[#26](https://github.com/Hexlet/ru-instructions/pull/26)]
