### ISSUE TITLE
Добавить инструкцию по установке terraform

### ISSUE THREAD

**Issue by ssssank** [Hexlet/ru-instructions#24]
Нужна инструкция по установке и запуску terraform. За основу можно взять [официальную инструкцию](https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli), а также можно подглядывать в другие инструкции из этого репозитория

**Comment by Skeler667** [comment]
Берусь за задачу

**Comment by Skeler667** [comment]
@ssssank Выполнил
