### ISSUE TITLE
Добавить инструкцию по установке redis

### ISSUE THREAD

**Issue by ssssank** [Hexlet/ru-instructions#28]
Нужна инструкция по установке и запуску redis. За основу можно взять [официальную инструкцию](https://redis.io/docs/getting-started/installation/), а также можно подглядывать в другие инструкции из этого репозитория и в этот [урок](https://ru.hexlet.io/courses/redis-basics/lessons/intro/theory_unit)

**Comment by SuperSnowSnail** [comment]
Взял в работу

**Comment by SuperSnowSnail** [comment]
Готово [#29]
